In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from plotly.offline import iplot
import plotly.graph_objs as go

from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
timesData = pd.read_csv("/content/timesData.csv")

In [4]:
timesData.head(12)

,world_rank,university_name,country,teaching,international,research,citations,income,total_score,num_students,student_staff_ratio,international_students,female_male_ratio,year
0,1,Harvard University,United States of America,99.7,72.4,98.7,98.8,34.5,96.1,"20,152",8.9,25%,NaN,2011
1,2,California Institute of Technology,United States of America,97.7,54.6,98.0,99.9,83.7,96.0,"2,243",6.9,27%,33 : 67,2011
2,3,Massachusetts Institute of Technology,United States of America,97.8,82.3,91.4,99.9,87.5,95.6,"11,074",9.0,33%,37 : 63,2011
3,4,Stanford University,United States of America,98.3,29.5,98.1,99.2,64.3,94.3,"15,596",7.8,22%,42 : 58,2011
4,5,Princeton University,United States of America,90.9,70.3,95.4,99.9,-,94.2,"7,929",8.4,27%,45 : 55,2011
5,6,University of Cambridge,United Kingdom,90.5,77.7,94.1,94.0,57.0,91.2,"18,812",11.8,34%,46 : 54,2011
6,6,University of Oxford,United Kingdom,88.2,77.2,93.9,95.1,73.5,91.2,"19,919",11.6,34%,46 : 54,2011
7,8,"University of California, Berkeley",United States of America,84.2,39.6,99.3,97.8,-,91.1,"36,186",16.4,15%,50 : 50,2011
8,9,Imperial College London,United Kingdom,89.2,90.0,94.5,88.3,92.9,90.6,"15,060",11.7,51%,37 : 63,2011
9,10,Yale University,United States of America,92.1,59.2,89.7,91.5,-,89.5,"11,751",4.4,20%,50 : 50,2011
10,11,"University of California, Los Angeles",United States of America,83.0,48.1,92.9,93.2,-,87.7,"38,206",10.3,15%,52 : 48,2011
11,12,University of Chicago,United States of America,79.1,62.8,87.9,96.9,-,86.9,"14,221",6.9,21%,42 : 58,2011

In [5]:
timesData.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2603 entries, 0 to 2602
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   world_rank              2603 non-null   object
 1   university_name         2603 non-null   object
 2   country                 2603 non-null   object
 3   teaching                2603 non-null   float64
 4   international           2603 non-null   object
 5   research                2603 non-null   float64
 6   citations               2603 non-null   float64
 7   income                  2603 non-null   object
 8   total_score             2603 non-null   object
 9   num_students            2544 non-null   object
 10  student_staff_ratio     2544 non-null   float64
 11  international_students  2536 non-null   object
 12  female_male_ratio       2370 non-null   object
 13  year                    2603 non-null   int64
dtypes: float64(4), int64(1), object(9)
memory usage: 284.8+ KB

In [6]:
y2015 = timesData[timesData.year == 2015]

In [7]:
international = [float(each) for each in y2015.international]

In [9]:
trace0 = go.Box(y = y2015.international,
                name = "International Score of Students in 2015",
                marker = dict(color = 'rgb(255,214,234)',)
)

In [10]:
trace1 = go.Box(y = y2015.income,
                name = "Income of Universities in 2015",
                marker = dict(color = 'rgb(255,111,222)'),
                )

In [11]:
data = [trace0, trace1]
iplot(data)